[phases.setup]
nixPkgs = [
  "python311Full", 
  "mesa", 
  "mesa.drivers",   # Provides libGL.so.1
  "libglvnd", 
  "glib",           
  "ffmpeg",         
  "xorg.libX11",    
  "xorg.libXext",   
  "xorg.libXrender",
  "tesseract"
]

[phases.build]
cmds = [
  "python -m ensurepip",
  "pip install --upgrade pip",
  "pip install --no-cache-dir -r requirements.txt --no-binary opencv-python opencv-python-headless"
]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --workers=2 --threads=2 --timeout 120"

